version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "11:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: electron-to-chromium
    versions:
    - 1.3.716
    - 1.3.723
  - dependency-name: caniuse-lite
    versions:
    - 1.0.30001208
    - 1.0.30001219
  - dependency-name: "@babel/helper-module-transforms"
    versions:
    - 7.12.13
    - 7.13.14
  - dependency-name: "@babel/helper-compilation-targets"
    versions:
    - 7.13.8
  - dependency-name: "@babel/helpers"
    versions:
    - 7.12.13
    - 7.13.0
  - dependency-name: "@babel/helper-member-expression-to-functions"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.13.0
  - dependency-name: "@babel/helper-replace-supers"
    versions:
    - 7.12.13
    - 7.13.0
  - dependency-name: "@babel/helper-simple-access"
    versions:
    - 7.12.13
  - dependency-name: "@babel/highlight"
    versions:
    - 7.12.13
  - dependency-name: "@babel/helper-function-name"
    versions:
    - 7.12.13
  - dependency-name: "@babel/helper-get-function-arity"
    versions:
    - 7.12.13
  - dependency-name: "@babel/helper-module-imports"
    versions:
    - 7.12.13
  - dependency-name: "@babel/helper-optimise-call-expression"
    versions:
    - 7.12.13
