version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "all"
    default_reviewers:
      - "alexswilliams"
    default_assignees:
      - "alexswilliams"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
