# This workflow will do a clean installation of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/tutorials/build-and-test-code/nodejs

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        node-version: ["26.x", "24.x", "22.x"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Rebuild assets
        run: make -B clean all

      - name: Run tests
        run: make test

      # Don't allow the check to pass if the minified js has changed
      # compared to what's committed - indicates manual remediation
      # required, and possibly a new npm release.
      - name: Ensure assets are deterministic and have no changes
        run: |
          [ $(git diff --name-only lib/orcid.min.js | wc -l) -eq 0 ]
          [ $(git diff --name-only lib/orcid.d.ts | wc -l) -eq 0 ]
