name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm ci

      - name: Lint source
        run: make lint

      - name: Rebuild assets
        run: make -B clean lib/orcid.min.js lib/orcid.d.ts

      - name: Run tests
        run: make test

      # Don't allow the check to pass if the minified js has changed
      # compared to what's committed - indicates manual remediation
      # required, and possibly a new npm release.
      - name: Ensure assets are deterministic and have no changes
        run: |
          [ $(git diff --name-only lib/orcid.min.js | wc -l) -eq 0 ]
          [ $(git diff --name-only lib/orcid.d.ts | wc -l) -eq 0 ]

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
